#!/bin/sh
# This is an example of what adding gitleaks to a pre-commit...

# Buscamos valor asignado: <> true no se ejecuta gitleaks
gitleaksEnabled=$(git config --bool hooks.gitleaks)

if [ "$gitleaksEnabled" = "true" ]; then
        gitleaks protect --staged -v
        if [ $? -eq 1 ]; then
                echo "\n>> pre-commit: Error: gitleaks protect has detected sensitive information in your changes."
                echo ">> pre-commit: No se realizará el commit"
                exit 1
        fi
fi