#!/bin/sh
# This is an example of what adding gitleaks to a pre-commit ...

gitleaks protect --staged -v
if [ $? -eq 1 ]; then
      echo "\n>> pre-commit: Error: gitleaks protect has detected sensitive information in your changes."
      echo ">> pre-commit: No se realizará el commit"
    exit 1
fi

flake8 $(git diff --name-only --cached | grep '.py$')
if [ $? -eq 1 ]; then
      echo "\n>> pre-commit: Error: flake8."
      echo ">> pre-commit: No se realizará el commit"
    exit 1
fi